export const mockedPosts = [
  {
    "id": "software-cost-calculator-mock",
    "title": "Software Cost Calculator",
    "description": "A clean and efficient Java utility to estimate the total cost of a software project based on lines of code, developer salary, productivity, testing, and contingency factors.",
    "type": "Code",
    "category": "Business",
    "tags": [
      "Java",
      "Estimation",
      "Management",
      "Utility",
      "Algorithm"
    ],
    "language": "Java",
    "framework": "Java SE",
    "difficulty": "Beginner",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 532,
    "saves_count": 241,
    "downloads_count": 156,
    "views_count": 2154,
    "average_rating": 4.8,
    "ratings_count": 42,
    "created_at": "2026-08-03T05:37:20.969Z",
    "content": "public class SoftwareCostCalculator {\n\n    public static class ProjectEstimate {\n        double effortPersonMonths;\n        double developmentCost;\n        double infrastructureCost;\n        double testingCost;\n        double contingencyCost;\n        double totalCost;\n\n        public ProjectEstimate(\n                double effortPersonMonths,\n                double developmentCost,\n                double infrastructureCost,\n                double testingCost,\n                double contingencyCost,\n                double totalCost) {\n            this.effortPersonMonths = effortPersonMonths;\n            this.developmentCost = developmentCost;\n            this.infrastructureCost = infrastructureCost;\n            this.testingCost = testingCost;\n            this.contingencyCost = contingencyCost;\n            this.totalCost = totalCost;\n        }\n\n        @Override\n        public String toString() {\n            return String.format(\n                \"===== Software Project Estimate =====\\n\" +\n                \"Effort              : %.2f person-months\\n\" +\n                \"Development Cost    : $%.2f\\n\" +\n                \"Infrastructure Cost : $%.2f\\n\" +\n                \"Testing Cost        : $%.2f\\n\" +\n                \"Contingency         : $%.2f\\n\" +\n                \"-------------------------------------\\n\" +\n                \"Total Estimated Cost: $%.2f\\n\" +\n                \"=====================================\",\n                effortPersonMonths, developmentCost, infrastructureCost, testingCost, contingencyCost, totalCost\n            );\n        }\n    }\n\n    public static ProjectEstimate calculateEstimate(\n            int linesOfCode, double developerSalaryPerMonth, int developers,\n            double productivityLOCPerPersonMonth, double infrastructurePerMonth,\n            double testingPercentage, double contingencyPercentage) {\n        \n        double effortPersonMonths = linesOfCode / productivityLOCPerPersonMonth;\n        double developmentCost = effortPersonMonths * developerSalaryPerMonth;\n        double projectDurationMonths = effortPersonMonths / developers;\n        double infrastructureCost = projectDurationMonths * infrastructurePerMonth;\n        double testingCost = developmentCost * (testingPercentage / 100);\n        double baseCost = developmentCost + infrastructureCost + testingCost;\n        double contingencyCost = baseCost * (contingencyPercentage / 100);\n        double totalCost = baseCost + contingencyCost;\n\n        return new ProjectEstimate(effortPersonMonths, developmentCost, infrastructureCost, testingCost, contingencyCost, totalCost);\n    }\n}",
    "readme_content": "# Software Cost Calculator\\n\\nA clean, professional Java utility designed to help project managers and developers estimate the total cost and required effort for a software project based on algorithmic models (similar to COCOMO)."
  },
  {
    "id": "intelligence-finder-mock",
    "title": "Intelligence Finder | Know Your Mind",
    "description": "Discover your true potential through the 9 Types of Intelligence. Take our 10-question assessment and find what makes your mind unique. A psychological tool for self-discovery.",
    "type": "Project",
    "category": "Website Development",
    "tags": [
      "Psychology",
      "Quiz",
      "Assessment",
      "Frontend",
      "Vercel"
    ],
    "language": "HTML/CSS/JS",
    "framework": "Vanilla JS",
    "difficulty": "Beginner",
    "license_type": "MIT",
    "preview_url": "/previews/intelligence-finder.png",
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 2451,
    "saves_count": 1042,
    "downloads_count": 856,
    "views_count": 12501,
    "average_rating": 4.9,
    "ratings_count": 215,
    "created_at": "2026-08-05T05:37:20.970Z",
    "content": "{\"files\":[{\"filename\":\"index.html\",\"extension\":\".html\",\"language\":\"html\",\"content\":\"<!DOCTYPE html>\\\\n<html lang=\\\"en\\\">\\\\n<head>\\\\n    <meta charset=\\\"UTF-8\\\">\\\\n    <title>Intelligence Finder</title>\\\\n    <link rel=\\\"stylesheet\\\" href=\\\"style.css\\\">\\\\n</head>\\\\n<body>\\\\n    <div id=\\\"app\\\"><h1>Discover Your Intelligence</h1></div>\\\\n    <script src=\\\"script.js\\\"></script>\\\\n</body>\\\\n</html>\"},{\"filename\":\"script.js\",\"extension\":\".js\",\"language\":\"javascript\",\"content\":\"const questions = [\\\\n  { text: 'Do you enjoy logic puzzles?', type: 'logical' },\\\\n  { text: 'Do you play an instrument?', type: 'musical' }\\\\n];\\\\n\\\\nfunction calculateScore(answers) {\\\\n  return 'You have Logical-Mathematical intelligence!';\\\\n}\"}]}",
    "readme_content": "# Intelligence Finder\\n\\n**Know Your Mind**\\n\\nDiscover your true potential through the 9 Types of Intelligence. Take our assessment and find what makes your mind unique.\\n\\n## Links\\n- **Live Demo**: [https://intelligence-finder.vercel.app/](https://intelligence-finder.vercel.app/)\\n- **GitHub Source**: [https://github.com/sunilkumar2007/Intelligence-Finder.git](https://github.com/sunilkumar2007/Intelligence-Finder.git)"
  },
  {
    "id": "benefit-bridge-mock",
    "title": "Benefit Bridge - Government Schemes Portal",
    "description": "A comprehensive digital initiative for a better India. Benefit Bridge helps you discover, understand, and apply for government schemes easily. Features include scheme matching, NGO portal, and multi-language support.",
    "type": "Project",
    "category": "Website Development",
    "tags": [
      "Government",
      "Schemes",
      "NGO",
      "Capacitor",
      "Vercel",
      "India"
    ],
    "language": "TypeScript",
    "framework": "React / Capacitor",
    "difficulty": "Advanced",
    "license_type": "MIT",
    "preview_url": "/previews/benefit-1.png",
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 512,
    "saves_count": 213,
    "downloads_count": 85,
    "views_count": 4501,
    "average_rating": 4.9,
    "ratings_count": 73,
    "created_at": "2026-07-29T05:37:20.970Z",
    "content": "{\"files\":[{\"filename\":\"scheme-matcher.ts\",\"extension\":\".ts\",\"language\":\"typescript\",\"content\":\"export function matchSchemes(profile: UserProfile, schemes: Scheme[]): Scheme[] {\\\\n  return schemes.filter(scheme => {\\\\n    const incomeMatch = profile.annualIncome <= scheme.maxIncome;\\\\n    const ageMatch = profile.age >= scheme.minAge && profile.age <= scheme.maxAge;\\\\n    return incomeMatch && ageMatch;\\\\n  });\\\\n}\"}]}",
    "readme_content": "# Benefit Bridge\\n\\nConnecting citizens with vital government schemes."
  },
  {
    "id": "react-glassmorphism-button",
    "title": "Premium Glassmorphism React Button",
    "description": "A stunning, fully accessible React button component using Tailwind CSS and Framer Motion for buttery smooth hover and click animations with a glassmorphism aesthetic.",
    "type": "Component",
    "category": "UI/UX",
    "tags": [
      "React",
      "Tailwind",
      "Framer Motion",
      "Glassmorphism",
      "UI"
    ],
    "language": "TypeScript",
    "framework": "React",
    "difficulty": "Intermediate",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 1420,
    "saves_count": 890,
    "downloads_count": 0,
    "views_count": 5020,
    "average_rating": 5,
    "ratings_count": 112,
    "created_at": "2026-08-06T05:37:20.970Z",
    "content": "import React from 'react';\nimport { motion } from 'framer-motion';\n\ninterface GlassButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\n  children: React.ReactNode;\n}\n\nexport const GlassButton: React.FC<GlassButtonProps> = ({ children, ...props }) => {\n  return (\n    <motion.button\n      whileHover={{ scale: 1.05 }}\n      whileTap={{ scale: 0.95 }}\n      className=\"relative px-6 py-3 font-semibold text-white bg-white/10 backdrop-blur-md border border-white/20 rounded-full shadow-[0_8px_32px_0_rgba(31,38,135,0.37)] hover:bg-white/20 transition-colors\"\n      {...props}\n    >\n      <span className=\"relative z-10\">{children}</span>\n      <div className=\"absolute inset-0 rounded-full bg-gradient-to-r from-white/0 via-white/5 to-white/0 opacity-0 hover:opacity-100 transition-opacity duration-500 blur-sm\" />\n    </motion.button>\n  );\n};",
    "readme_content": "# Glassmorphism Button\\n\\nUse this component in any React/Tailwind project to instantly upgrade your UI."
  },
  {
    "id": "python-web-scraper",
    "title": "Concurrent Python Web Scraper",
    "description": "A highly efficient, concurrent Python web scraper using BeautifulSoup and ThreadPoolExecutor. Designed to scrape thousands of pages per minute safely.",
    "type": "Code",
    "category": "Data Science",
    "tags": [
      "Python",
      "Scraping",
      "BeautifulSoup",
      "Concurrency",
      "Data"
    ],
    "language": "Python",
    "framework": "None",
    "difficulty": "Advanced",
    "license_type": "Apache 2.0",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 843,
    "saves_count": 612,
    "downloads_count": 0,
    "views_count": 3100,
    "average_rating": 4.7,
    "ratings_count": 56,
    "created_at": "2026-08-07T05:37:20.970Z",
    "content": "import concurrent.futures\nimport requests\nfrom bs4 import BeautifulSoup\n\nURLS = [\n    'http://example.com/page1',\n    'http://example.com/page2',\n    'http://example.com/page3',\n    # Add your thousands of URLs here\n]\n\ndef fetch_and_parse(url):\n    try:\n        response = requests.get(url, timeout=5)\n        response.raise_for_status()\n        soup = BeautifulSoup(response.text, 'html.parser')\n        \n        # Example extraction: Get all H1 tags\n        h1_tags = [h1.text.strip() for h1 in soup.find_all('h1')]\n        \n        return {'url': url, 'data': h1_tags, 'status': 'success'}\n    except Exception as e:\n        return {'url': url, 'error': str(e), 'status': 'failed'}\n\ndef scrape_all_urls(urls, max_workers=10):\n    results = []\n    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:\n        future_to_url = {executor.submit(fetch_and_parse, url): url for url in urls}\n        for future in concurrent.futures.as_completed(future_to_url):\n            url = future_to_url[future]\n            try:\n                data = future.result()\n                results.append(data)\n                print(f\"Completed: {url}\")\n            except Exception as exc:\n                print(f\"{url} generated an exception: {exc}\")\n    return results\n\nif __name__ == '__main__':\n    scraped_data = scrape_all_urls(URLS)\n    print(f\"Scraped {len(scraped_data)} pages.\")",
    "readme_content": "# Concurrent Scraper\\n\\nMake sure to respect `robots.txt` and use rate limiting if targeting a single domain!"
  },
  {
    "id": "system-architecture-prompt",
    "title": "Senior Solutions Architect Prompt",
    "description": "A mega-prompt designed to turn Claude or ChatGPT into a Senior Solutions Architect. It forces the AI to output sequence diagrams, database schemas, and cost estimates.",
    "type": "Prompt",
    "category": "Website Development",
    "tags": [
      "Prompt",
      "Architecture",
      "System Design",
      "ChatGPT",
      "AI"
    ],
    "language": "Text",
    "framework": "None",
    "difficulty": "Beginner",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 3210,
    "saves_count": 2900,
    "downloads_count": 0,
    "views_count": 15000,
    "average_rating": 5,
    "ratings_count": 412,
    "created_at": "2026-08-01T05:37:20.970Z",
    "content": "Act as a Principal Solutions Architect at a FAANG company.\n\nI am going to provide you with a high-level product requirement. Your job is to design a highly scalable, fault-tolerant, and cost-effective system architecture to fulfill these requirements.\n\nYour response MUST follow this exact structure:\n\n1. EXECUTIVE SUMMARY: A 2-paragraph summary of the chosen architecture.\n2. COMPONENT DESIGN: A bulleted list of all microservices, databases, and message queues required. Explain WHY you chose each specific technology (e.g., PostgreSQL vs MongoDB, Kafka vs RabbitMQ).\n3. DATA MODEL: Provide the core database schemas in SQL or NoSQL format.\n4. SEQUENCE DIAGRAM: Write a Mermaid.js sequence diagram showing the core user flow (e.g., user signup, placing an order).\n5. BOTTLENECKS & SCALING: Identify the single points of failure and how you will mitigate them.\n6. COST ESTIMATE: Provide a rough monthly AWS/GCP cost estimate for 10,000 DAU vs 1,000,000 DAU.\n\nDo not write any code other than the Mermaid diagram and SQL schemas. Wait for me to provide the product requirement before starting.",
    "readme_content": "# System Architect Prompt\\n\\nJust copy and paste this into ChatGPT or Claude, and then reply with your app idea (e.g., 'I want to build a real-time multiplayer chess game')."
  },
  {
    "id": "docker-compose-boilerplate",
    "title": "Ultimate Docker Compose Boilerplate",
    "description": "The only docker-compose.yml you need for local development. Includes Node.js, PostgreSQL, Redis, and PgAdmin wired up in a custom network with persistent volumes.",
    "type": "Code",
    "category": "Website Development",
    "tags": [
      "Docker",
      "DevOps",
      "PostgreSQL",
      "Redis",
      "Node"
    ],
    "language": "YAML",
    "framework": "Docker",
    "difficulty": "Beginner",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 1820,
    "saves_count": 1400,
    "downloads_count": 0,
    "views_count": 6000,
    "average_rating": 4.9,
    "ratings_count": 88,
    "created_at": "2026-08-04T05:37:20.970Z",
    "content": "version: '3.8'\n\nservices:\n  api:\n    build:\n      context: ./api\n      dockerfile: Dockerfile.dev\n    volumes:\n      - ./api:/usr/src/app\n      - /usr/src/app/node_modules\n    ports:\n      - \"3000:3000\"\n    environment:\n      - DATABASE_URL=postgres://postgres:password@db:5432/myapp\n      - REDIS_URL=redis://redis:6379\n    depends_on:\n      db:\n        condition: service_healthy\n      redis:\n        condition: service_started\n    networks:\n      - app-network\n\n  db:\n    image: postgres:15-alpine\n    environment:\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: password\n      POSTGRES_DB: myapp\n    ports:\n      - \"5432:5432\"\n    volumes:\n      - postgres_data:/var/lib/postgresql/data\n    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -U postgres\"]\n      interval: 5s\n      timeout: 5s\n      retries: 5\n    networks:\n      - app-network\n\n  redis:\n    image: redis:7-alpine\n    ports:\n      - \"6379:6379\"\n    volumes:\n      - redis_data:/data\n    networks:\n      - app-network\n\n  pgadmin:\n    image: dpage/pgadmin4\n    environment:\n      PGADMIN_DEFAULT_EMAIL: admin@admin.com\n      PGADMIN_DEFAULT_PASSWORD: root\n    ports:\n      - \"5050:80\"\n    depends_on:\n      - db\n    networks:\n      - app-network\n\nnetworks:\n  app-network:\n    driver: bridge\n\nvolumes:\n  postgres_data:\n  redis_data:",
    "readme_content": "# Docker Compose Boilerplate\\n\\nRun `docker-compose up -d` and you'll have your entire backend infrastructure running locally in seconds."
  },
  {
    "id": "midjourney-ui-prompt",
    "title": "Futuristic Cyberpunk UI Midjourney Prompt",
    "description": "A carefully crafted Midjourney prompt to generate stunning, highly detailed futuristic user interfaces for web and mobile apps.",
    "type": "Prompt",
    "category": "UI/UX",
    "tags": [
      "Midjourney",
      "AI Art",
      "Prompt",
      "Cyberpunk",
      "Design"
    ],
    "language": "Text",
    "framework": "None",
    "difficulty": "Beginner",
    "license_type": "None",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 2100,
    "saves_count": 1800,
    "downloads_count": 0,
    "views_count": 8000,
    "average_rating": 4.8,
    "ratings_count": 150,
    "created_at": "2026-07-27T05:37:20.970Z",
    "content": "/imagine prompt: A highly detailed, futuristic cyberpunk dashboard UI design for a web application, dark mode, glowing neon cyan and magenta accents, holographic charts, glassmorphism panels, complex data visualization, intricate tech details, sharp vector graphics, clean typography, 8k resolution, photorealistic, cinematic lighting, UI/UX, dribbble style --ar 16:9 --v 6.0 --style raw --stylize 250",
    "readme_content": "# Cyberpunk UI Generator\\n\\nUse this in Midjourney v6 to generate incredible inspiration for your next dark-mode dashboard."
  },
  {
    "id": "go-worker-pool",
    "title": "Golang High-Performance Worker Pool",
    "description": "A robust, channel-based worker pool in Go for concurrent task processing. Includes graceful shutdown and error handling.",
    "type": "Code",
    "category": "Code",
    "tags": [
      "Golang",
      "Concurrency",
      "Backend",
      "Worker Pool",
      "Performance"
    ],
    "language": "Go",
    "framework": "None",
    "difficulty": "Advanced",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 670,
    "saves_count": 500,
    "downloads_count": 0,
    "views_count": 2500,
    "average_rating": 4.9,
    "ratings_count": 40,
    "created_at": "2026-08-02T05:37:20.970Z",
    "content": "package main\n\nimport (\n\t\"fmt\"\n\t\"sync\"\n\t\"time\"\n)\n\ntype Job struct {\n\tID    int\n\tValue int\n}\n\ntype Result struct {\n\tJob Job\n\tErr error\n}\n\nfunc worker(id int, jobs <-chan Job, results chan<- Result, wg *sync.WaitGroup) {\n\tdefer wg.Done()\n\tfor j := range jobs {\n\t\tfmt.Printf(\"Worker %d started job %d\\n\", id, j.ID)\n\t\ttime.Sleep(time.Millisecond * 500) // Simulate expensive work\n\t\tfmt.Printf(\"Worker %d finished job %d\\n\", id, j.ID)\n\t\t\n\t\tresults <- Result{Job: j, Err: nil}\n\t}\n}\n\nfunc main() {\n\tconst numJobs = 20\n\tconst numWorkers = 5\n\n\tjobs := make(chan Job, numJobs)\n\tresults := make(chan Result, numJobs)\n\tvar wg sync.WaitGroup\n\n\t// Start workers\n\tfor w := 1; w <= numWorkers; w++ {\n\t\twg.Add(1)\n\t\tgo worker(w, jobs, results, &wg)\n\t}\n\n\t// Send jobs\n\tfor j := 1; j <= numJobs; j++ {\n\t\tjobs <- Job{ID: j, Value: j * 10}\n\t}\n\tclose(jobs) // Close jobs channel to signal no more work\n\n\t// Wait in a separate goroutine so we can close results\n\tgo func() {\n\t\twg.Wait()\n\t\tclose(results)\n\t}()\n\n\t// Collect results\n\tfor res := range results {\n\t\tif res.Err != nil {\n\t\t\tfmt.Printf(\"Job %d failed: %v\\n\", res.Job.ID, res.Err)\n\t\t} else {\n\t\t\tfmt.Printf(\"Job %d succeeded.\\n\", res.Job.ID)\n\t\t}\n\t}\n}",
    "readme_content": "# Go Worker Pool\\n\\nStandard library concurrency pattern for handling thousands of jobs across a fixed number of goroutines."
  },
  {
    "id": "nextjs-auth-middleware",
    "title": "Next.js App Router Auth Middleware",
    "description": "A secure, edge-compatible middleware for Next.js 14+ App Router to protect routes using JWT tokens.",
    "type": "Code",
    "category": "Website Development",
    "tags": [
      "Next.js",
      "React",
      "Authentication",
      "Middleware",
      "Security"
    ],
    "language": "TypeScript",
    "framework": "Next.js",
    "difficulty": "Intermediate",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 1150,
    "saves_count": 920,
    "downloads_count": 0,
    "views_count": 4800,
    "average_rating": 4.8,
    "ratings_count": 95,
    "created_at": "2026-07-31T05:37:20.970Z",
    "content": "import { NextResponse } from 'next/server';\nimport type { NextRequest } from 'next/server';\nimport { jwtVerify } from 'jose';\n\n// Define public routes that don't require authentication\nconst publicRoutes = ['/login', '/register', '/api/auth/login'];\n\nexport async function middleware(request: NextRequest) {\n  const { pathname } = request.nextUrl;\n  \n  // 1. Allow public routes\n  if (publicRoutes.some(route => pathname.startsWith(route))) {\n    return NextResponse.next();\n  }\n\n  // 2. Check for token in cookies\n  const token = request.cookies.get('auth-token')?.value;\n\n  if (!token) {\n    // No token, redirect to login\n    const loginUrl = new URL('/login', request.url);\n    loginUrl.searchParams.set('callbackUrl', pathname);\n    return NextResponse.redirect(loginUrl);\n  }\n\n  try {\n    // 3. Verify JWT token using edge-compatible 'jose' library\n    const secret = new TextEncoder().encode(process.env.JWT_SECRET);\n    await jwtVerify(token, secret);\n    \n    // Token is valid, allow request\n    return NextResponse.next();\n  } catch (error) {\n    // Token is invalid or expired\n    const loginUrl = new URL('/login', request.url);\n    loginUrl.searchParams.set('error', 'session_expired');\n    \n    const response = NextResponse.redirect(loginUrl);\n    // Clear the invalid cookie\n    response.cookies.delete('auth-token');\n    return response;\n  }\n}\n\nexport const config = {\n  // Run middleware on all routes except static files and images\n  matcher: ['/((?!_next/static|_next/image|favicon.ico|public/).*)'],\n};",
    "readme_content": "# Next.js Auth Middleware\\n\\nDrop this `middleware.ts` into the root of your Next.js 14 App Router project to instantly secure your dashboard routes."
  },
  {
    "id": "srs-prompt-generator",
    "title": "SRS to Prompt Pipeline Generator",
    "description": "An interactive meta-prompt that turns ChatGPT or Claude into a project manager. Provide it with your Software Requirements Specification (SRS), tell it how many phases you want, and it will generate exactly that many detailed implementation prompts for you to use.",
    "type": "Prompt",
    "category": "Productivity",
    "tags": [
      "Prompt",
      "Project Management",
      "SRS",
      "Planning",
      "AI"
    ],
    "language": "Text",
    "framework": "None",
    "difficulty": "Intermediate",
    "license_type": "MIT",
    "preview_url": null,
    "creator_id": "mock-creator-id",
    "creator": {
      "username": "sunilkumar",
      "full_name": "Sunil Kumar",
      "avatar_url": null,
      "bio": "Designing future interfaces and exploring AI creative potential. London based."
    },
    "likes_count": 5120,
    "saves_count": 4800,
    "downloads_count": 0,
    "views_count": 22000,
    "average_rating": 5,
    "ratings_count": 890,
    "created_at": "2026-08-07T05:37:20.970Z",
    "content": "You are an expert AI Technical Project Manager and Systems Architect. Your goal is to help me break down a complex Software Requirements Specification (SRS) into a series of highly actionable, sequential implementation prompts that I can feed back into an AI (like yourself) to build the software.\n\nHere is how we will proceed:\n\n**Step 1: Ingestion**\nI will provide you with the full text of my SRS document or a detailed description of the software I want to build. You will read it and confirm you understand the core requirements, tech stack, and objectives.\n\n**Step 2: Phase Assessment**\nYou will ask me: \"How many phases would you like to break this implementation into?\"\n\n**Step 3: Prompt Generation**\nOnce I reply with a number (N), you will generate exactly N distinct, highly detailed prompts. \n\nEach generated prompt MUST follow this structure:\n- **Phase Context**: A brief summary of what was accomplished in previous phases so the AI knows where it is starting from.\n- **Phase Objective**: What specifically needs to be built in this phase.\n- **Specific Tasks**: A bulleted list of components, API endpoints, database schemas, or UI elements to create.\n- **Output Requirements**: Clear instructions on how the AI should output the code (e.g., \"Provide the complete file contents for X and Y, do not use placeholders\").\n\nDo not generate the prompts until I have provided the SRS and told you how many phases I want. \n\nIf you understand these instructions, reply with: \"I am ready. Please provide your Software Requirements Specification (SRS).\"",
    "readme_content": "# SRS Pipeline Generator\\n\\nPaste this into any advanced LLM. It will ask for your SRS, ask how many phases you want to break the project into, and then generate highly optimized prompts for each phase of your build!"
  }
];