/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ResourcesIdRouteImport } from './routes/resources/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/categories': typeof CategoriesRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/seed': typeof SeedRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/categories': typeof CategoriesRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/seed': typeof SeedRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/categories': typeof CategoriesRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/seed': typeof SeedRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/categories'
    | '/create'
    | '/explore'
    | '/feed'
    | '/seed'
    | '/profile/$username'
    | '/resources/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/categories'
    | '/create'
    | '/explore'
    | '/feed'
    | '/seed'
    | '/profile/$username'
    | '/resources/$id'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/categories'
    | '/create'
    | '/explore'
    | '/feed'
    | '/seed'
    | '/profile/$username'
    | '/resources/$id'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CategoriesRoute: typeof CategoriesRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  SeedRoute: typeof SeedRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ResourcesIdRoute: typeof ResourcesIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CategoriesRoute: CategoriesRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  SeedRoute: SeedRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ResourcesIdRoute: ResourcesIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
